name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/Sabbaken/bc-text-moderation/bc-text-moderation
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN_GITHUB}}
          tags: "production"